# Generated by Django 5.2.5 on 2025-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0002_recentcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='company_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='directory',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
